CREATE DATABASE SALES;
USE SALES;


SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM PAYMENTS;

--CUSTOMERS FROM MUMBAI
SELECT * FROM CUSTOMERS
WHERE CITY = 'MUMBAI';
/*
CustomerID	   FirstName	LastName	Gender	City	SignupDate
1	           Amit	        Shah	    Male	Mumbai	2023-02-10
6	           Priya	    Nair	    Female	Mumbai	2023-08-30
Identified customers from Mumbai to analyze specific region customers.
*/

SELECT * FROM PRODUCTS
WHERE CATEGORY = 'ELECTRONICS';
/*
ProductID	ProductName	Category	Price
101	        Smartphone	Electronics	15000
102	        Headphones	Electronics	2000
105         Laptop	    Electronics	55000
108	        Tablet	    Electronics	22000
ELECTRONIC CATEGORY SELLS PRODUCTS SUCH AS SMARTPHONE,HEADPHONES,LAPTOP,TABLET.
*/


SELECT * FROM CUSTOMERS
WHERE SIGNUPDATE > '2023-12-31';
/*
CustomerID	FirstName	LastName	Gender	City	  SignupDate
3	        Raj	        Mehta	    Male	Delhi	  2024-01-05
5	        Vikram	    Rao	        Male	Bangalore 2024-03-22
7	        Karan	    Malhotra	Male	Delhi	  2024-06-14
9	        Rohit	    Sen	        Male	Kolkata	  2024-02-17
Identified newly acquired customers in 2024 to understand recent customer growth.
*/


SELECT * FROM PRODUCTS
WHERE PRICE BETWEEN 500 AND 2000;
/*
ProductID	ProductName	Category	Price
102	        Headphones	Electronics	2000
104	        T-Shirt	    Fashion	    1200
107	        Backpack	Accessories	1800
109	        Sunglasses	Accessories	900
110	        Jeans	    Fashion	    2000
Filtered products priced between 500 and 2000 to analyze mid-range product offerings.
*/


--CUSTOMER BASE
SELECT COUNT(*) AS NO_OF_CUSTOMERS FROM CUSTOMERS;
/*
NO_OF_CUSTOMERS
10
Determined that the total customer base consisting of 10 customers.
*/


--GENERAL PRICING OF PRODUCTS
SELECT AVG(PRICE) AS AVG_PRICE FROM PRODUCTS;
/*
AVG_PRICE
10540
Calculated the average product price to understand general pricing level in the business.
*/

SELECT DISTINCT City
FROM Customers;
SELECT COUNT(DISTINCT City) AS NO_OF_CITIES FROM Customers;
/*
City
Ahmedabad
Bangalore
Chennai
Delhi
Kolkata
Mumbai
Pune

NO_OF_CITIES
7
Identified all unique cities to understand the distribution of customers.
*/


SELECT * FROM ORDERS
WHERE MONTH(ORDERDATE) = '3' AND YEAR(ORDERDATE) = '2024';
/*
OrderID	CustomerID	OrderDate
1001	1	        2024-03-10
1002	2	        2024-03-12
Analyzed orders placed in March 2024 to understand monthly sales activity.
*/

SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE 'S%';
/*
ProductID	ProductName	Category	Price
101	        Smartphone	Electronics	15000
103	        Shoes	    Fashion	    3000
109	        Sunglasses	Accessories	900
Identified products starting with 'S' to analyze naming patterns in the product catalog
*/


SELECT TOP 1 * FROM PRODUCTS
ORDER BY PRICE DESC;
/*
ProductID	ProductName	Category	Price
105	        Laptop	    Electronics	55000
Determined that Laptop is the most expensive product in the dataset.
*/


SELECT C.FIRSTNAME,C.LASTNAME,O.ORDERDATE FROM CUSTOMERS C
INNER JOIN ORDERS O 
ON
C.CUSTOMERID = O.CUSTOMERID;
/*
FIRSTNAME	ORDERDATE
Amit	    2024-03-10
Amit	    2024-06-02
Neha	    2024-03-12
Raj	        2024-04-01
Sneha	    2024-04-05
Vikram	    2024-05-18
Priya	    2024-06-15
Karan	    2024-07-10
Anjali	    2024-07-22
Rohit	    2024-08-03
Mapped customers with their order dates to understand purchasing activity over time.
*/


SELECT O.ORDERID,P.PRODUCTNAME,OD.QUANTITY FROM ORDERS O
INNER JOIN ORDER_DETAILS OD
ON
O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P
ON 
P.PRODUCTID = OD.PRODUCTID;
/*
ORDERID	PRODUCTNAME	QUANTITY
1001	Smartphone	1
1001	Headphones	2
1002	Shoes	    1
1003	T-Shirt	    3
1004	Laptop	    1
1005	Watch	    2
1006	Backpack	1
1007	Tablet	    1
1008	Sunglasses	4
1009	Jeans	    2
Identified products and quantities within each order to analyze order composition.
*/


SELECT O.ORDERID,SUM(OD.QUANTITY * P.PRICE) AS REVENUE FROM ORDERS O
INNER JOIN ORDER_DETAILS OD
ON
O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P
ON
P.PRODUCTID = OD.PRODUCTID
GROUP BY O.ORDERID;
/*
ORDERID	REVENUE
1001	19000
1002	3000
1003	3600
1004	55000
1005	5000
1006	1800
1007	22000
1008	3600
1009	4000
Calculated revenue generated by each order to evaluate order-level earnings.
*/

SELECT C.FIRSTNAME,SUM(OD.QUANTITY * P.PRICE) AS REVENUE FROM CUSTOMERS C
INNER JOIN ORDERS O
ON
C.CUSTOMERID = O.CUSTOMERID
INNER JOIN ORDER_DETAILS OD
ON
O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P
ON
OD.PRODUCTID = P.PRODUCTID
GROUP BY C.FIRSTNAME
ORDER BY REVENUE DESC;
/*
FIRSTNAME	REVENUE
Sneha	    55000
Priya	    22000
Amit	    20800
Vikram	    5000
Anjali	    4000
Karan	    3600
Raj     	3600
Neha	    3000
Identified high spending customers based on their total purchase value.
*/

SELECT p.ProductName, SUM(od.Quantity) AS TotalSold
FROM Order_Details od
JOIN Products p ON 
od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalSold DESC;
/*
ProductName	TotalSold
Sunglasses	4
T-Shirt	    3
Watch	    2
Headphones	2
Jeans	    2
Laptop	    1
Shoes	    1
Smartphone	1
Tablet	    1
Backpack	1
Sunglasses are with highest sales volume.
*/


--TOP 5 SOLD PRODUCTS
SELECT TOP 5 p.ProductName, SUM(OD.Quantity) AS TotalSold
FROM Order_Details OD
JOIN Products p ON 
od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalSold DESC;
/*
ProductName	TotalSold
Sunglasses	4
T-Shirt	    3
Jeans	    2
Headphones	2
Watch	    2
Identified top 5 best-selling products contributing most to sales volume.
*/

--NUMBER OF ORDERS PER CITY
SELECT C.City,COUNT(O.OrderID) AS ORDERS_PER_CITY FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON
C.CustomerID = O.CustomerID
GROUP BY C.City
ORDER BY ORDERS_PER_CITY DESC;
/*
City	   ORDERS_PER_CITY
Mumbai	    3
Pune	    2
Delhi	    2
Kolkata	    1
Bangalore	1
Chennai	    1
Ahmedabad	0
Mumbai city orders the most . Identified the city to analyse the regional demand.
*/

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;

SELECT p.Category, SUM(od.Quantity * p.Price) AS Revenue
FROM Order_Details OD
JOIN Products p ON OD.ProductID = p.ProductID
GROUP BY p.Category
ORDER BY Revenue DESC;
/*
Category	Revenue
Electronics	96000
Fashion	    10600
Accessories	10400
Compared revenue contribution across product categories.
*/



SELECT C.FirstName,COUNT(O.ORDERID)AS ORDERCOUNT FROM CUSTOMERS C
INNER JOIN ORDERS O
ON
C.CustomerID = O.CustomerID
GROUP BY C.FirstName
HAVING COUNT(O.ORDERID) >= 3 ;
/*
No customer has placed more than 3 orders.
*/



SELECT * FROM PAYMENTS;
SELECT TOP 1 PaymentMode ,COUNT(PAYMENTID)  AS MOST_USED_PAYMENTMETHOD FROM PAYMENTS
GROUP BY PaymentMode
ORDER BY MOST_USED_PAYMENTMETHOD DESC;
/*
PaymentMode	MOST_USED_PAYMENTMETHOD
Card	    4
Card is the most preferred payment method among customers.
*/


SELECT MONTH(ORDERDATE) AS MONTH_NUM,SUM(OD.QUANTITY * P.PRICE) AS REVENUE FROM ORDERS O
INNER JOIN ORDER_DETAILS OD
ON 
O.OrderID = OD.OrderID
INNER JOIN PRODUCTS P
ON
OD.ProductID = P.ProductID
WHERE YEAR(ORDERDATE) = '2024'
GROUP BY MONTH(ORDERDATE);
/*
MONTH_NUM	REVENUE
3	        22000
4	        58600
5	        5000
6	        23800
7	        7600
Analyzed monthly revenue trends for the year 2024
*/


SELECT C.FirstName FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON 
C.CustomerID = O.CustomerID
WHERE O.OrderID IS NULL;
/*
FirstName
Meera
Meera has not placed any orders.
*/

SELECT TOP 2 * FROM PRODUCTS
ORDER BY PRICE DESC;
/*
ProductID	ProductName	Category	Price
105	        Laptop	    Electronics	55000
108	        Tablet	    Electronics	22000

*/

SELECT PRODUCTNAME, TOTALSOLD
FROM 
    (SELECT P.PRODUCTNAME,SUM(OD.QUANTITY) AS TOTALSOLD,
    DENSE_RANK() 
    OVER
    (ORDER BY SUM(OD.QUANTITY) DESC) AS RNK
    FROM ORDER_DETAILS OD
    JOIN PRODUCTS P
    ON
    OD.PRODUCTID = P.PRODUCTID
    GROUP BY P.PRODUCTNAME
    )
    T
    WHERE RNK = 2;
/*
PRODUCTNAME	TOTALSOLD
T-Shirt	     3
Tshirt is the second highest selling product based on total quantity sold.
*/


SELECT C.FirstName,SUM(OD.Quantity * P.PRICE) AS SPENDING,
RANK() 
OVER 
(ORDER BY SUM(OD.QUANTITY * P.PRICE) DESC) AS RNK
FROM CUSTOMERS C
JOIN ORDERS O 
ON
C.CustomerID = O.CustomerID
JOIN ORDER_DETAILS OD
ON
O.OrderID = OD.OrderID
JOIN PRODUCTS P
ON
OD.ProductID = P.ProductID
GROUP BY C.FirstName;
/*
FirstName	SPENDING	RNK
Sneha	    55000	    1
Priya	    22000	    2
Amit	    20800	    3
Vikram	    5000	    4
Anjali	    4000	    5
Karan       3600	    6
Raj	        3600	    6
Neha	    3000	    8
Ranked customers based on total spending to identify top contributors
*/


SELECT ORDERDATE,SUM(REVENUE) 
OVER
(ORDER BY ORDERDATE DESC) AS RUNNING_TOTAL
FROM(
SELECT O.OrderDate,SUM(OD.QUANTITY * P.PRICE) AS REVENUE FROM ORDERS O 
JOIN ORDER_DETAILS OD
ON
O.OrderID = OD.OrderID
JOIN PRODUCTS P
ON 
OD.ProductID = P.ProductID
GROUP BY O.OrderDate)
T;
/*
ORDERDATE	RUNNING_TOTAL
2024-07-22	4000
2024-07-10	7600
2024-06-15	29600
2024-06-02	31400
2024-05-18	36400
2024-04-05	91400
2024-04-01	95000
2024-03-12	98000
2024-03-10	117000
Calculated cumulative revenue over time to analyze sales growth trend.
*/

SELECT * FROM(
SELECT C.City, C.FirstName,SUM(OD.QUANTITY * P.PRICE) AS REVENUE,
RANK() 
OVER
(PARTITION BY C.CITY ORDER BY SUM(OD.QUANTITY * P.PRICE) DESC ) AS RNK
FROM CUSTOMERS C
JOIN ORDERS O 
ON
C.CustomerID = O.CustomerID
JOIN ORDER_DETAILS OD
ON
O.OrderID = OD.OrderID
JOIN PRODUCTS P
ON
OD.ProductID = P.ProductID
GROUP BY C.City,C.FirstName)
T
WHERE RNK = 1;
/*
City	    FirstName	REVENUE	RNK
Bangalore	Vikram	    5000	1
Chennai  	Sneha	    55000	1
Delhi	    Karan	    3600	1
Delhi	    Raj	        3600	1
Mumbai	    Priya	    22000	1
Pune	    Anjali	    4000	1
Identified top spending customer in each city.
*/


SELECT FIRSTNAME,REVENUE, 
CASE
    WHEN REVENUE > 5000 THEN 'GOLD'
    WHEN REVENUE BETWEEN 2000 AND 5000 THEN 'SILVER'
    ELSE 'BRONZE'
END AS CATEGORY
FROM (
SELECT C.FirstName,SUM(OD.QUANTITY * P.PRICE) AS REVENUE
FROM CUSTOMERS C
JOIN ORDERS O 
ON
C.CustomerID = O.CustomerID
JOIN ORDER_DETAILS OD
ON
O.OrderID = OD.OrderID
JOIN PRODUCTS P
ON
OD.ProductID = P.ProductID
GROUP BY C.FirstName)
T;
/*
FIRSTNAME	REVENUE	CATEGORY
Amit	    20800	GOLD
Anjali	    4000	SILVER
Karan	    3600	SILVER
Neha	    3000	SILVER
Priya	    22000	GOLD
Raj	        3600	SILVER
Sneha	    55000	GOLD
Vikram	    5000	SILVER
Segmented customers into Gold, Silver, and Bronze based on spending behavior.
*/

SELECT p.ProductName
FROM Products p
LEFT JOIN Order_Details od ON p.ProductID = od.ProductID
WHERE od.ProductID IS NULL;

SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMERS;


SELECT c.FirstName
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.FirstName
HAVING MAX(o.OrderDate) < DATEADD(MONTH, -6, GETDATE());
/*
FirstName
Amit
Anjali
Karan
Neha
Priya
Raj
Rohit
Sneha
Vikram
Identified customers who have not placed orders in the last 6 months.
*/

SELECT c.FirstName,
AVG(od.Quantity * p.Price) AS AvgOrderValue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN Order_Details od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY c.FirstName;
/*
FirstName	AvgOrderValue
Amit	    6933
Anjali	    4000
Karan	    3600
Neha	    3000
Priya	    22000
Raj	        3600
Sneha	    55000
Vikram	    5000
Calculated average order value for each customer to understand spending patterns.
*/


SELECT TOP 1 MONTH(o.OrderDate) AS Month,
SUM(od.Quantity * p.Price) AS Revenue
FROM Orders o
JOIN Order_Details od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY MONTH(o.OrderDate)
ORDER BY Revenue DESC;
/*
Month	Revenue
4	    58600
Identified the month generating highest revenue.
*/


WITH MonthlyOrders AS (
SELECT c.CustomerID, MONTH(o.OrderDate) AS Month
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, MONTH(o.OrderDate)
)
SELECT CustomerID
FROM MonthlyOrders
GROUP BY CustomerID
HAVING COUNT(Month) >= 3;


SELECT Category,
SUM(Revenue) * 100.0 / SUM(SUM(Revenue)) OVER() AS Percentage
FROM (
    SELECT p.Category, SUM(od.Quantity * p.Price) AS Revenue
    FROM Order_Details od
    JOIN Products p ON od.ProductID = p.ProductID
    GROUP BY p.Category
) t
GROUP BY Category;
/*
Category	Percentage
Accessories	8.888888888888
Electronics	82.051282051282
Fashion	    9.059829059829
Calculated percentage contribution of each category to total revenue.
*/



SELECT OrderID, TotalAmount
FROM (
    SELECT o.OrderID, SUM(od.Quantity * p.Price) AS TotalAmount
    FROM Orders o
    JOIN Order_Details od ON o.OrderID = od.OrderID
    JOIN Products p ON od.ProductID = p.ProductID
    GROUP BY o.OrderID
) t
WHERE TotalAmount > (
    SELECT AVG(TotalAmount)
    FROM (
        SELECT SUM(od.Quantity * p.Price) AS TotalAmount
        FROM Orders o
        JOIN Order_Details od ON o.OrderID = od.OrderID
        JOIN Products p ON od.ProductID = p.ProductID
        GROUP BY o.OrderID
    ) x
);
/*
OrderID	TotalAmount
1001	19000
1004	55000
1007	22000
Identified orders with value higher than average to detect high-value transactions.
*/